/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.component;

import com.sun.javafx.image.impl.ByteIndexed;
import javax.swing.JLabel;
import javax.swing.JTextField;
import silab.sd.personapp.view.component.exception.ValidatorException;
import silab.sd.personapp.view.component.validator.Validator;

/**
 *
 * @author Ema
 */
public class InputTextfieldPanel extends javax.swing.JPanel implements GetValue{
    private Validator validator; 
    /**
     * Creates new form InputTextfieldPanel
     */
    public InputTextfieldPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblErrorValue = new javax.swing.JLabel();

        lblText.setText("Text:");

        lblErrorValue.setForeground(new java.awt.Color(255, 0, 102));
        lblErrorValue.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorValue, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(txtValue))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorValue)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public JLabel getLblText() {
        return lblText;
    }

    public JTextField getTxtValue() {
        return txtValue;
    }

    @Override
    public Object getValue() throws Exception{
        lblErrorValue.setText("");
//        if (txtValue.getText().isEmpty()) {
//            lblErrorValue.setText("Polje je obavezno");
//            throw new Exception("Polje je obavezno");
//        }
        try {
            if (validator != null) validator.validate(txtValue.getText().trim());
            return txtValue.getText();
        } catch(ValidatorException ve){
            lblErrorValue.setText(ve.getMessage());
            throw new Exception(ve.getMessage());
        }
    }

    public void setValidator(Validator validator) {
        this.validator = validator;
    }
    
}
